# プレイヤーを飛ばす威力

velocity: 2.0

# 当たり判定の距離 (プレイヤー同士、足場の回収)

distance: 1.0

# 加速のポーションエフェクト効果 (duration は tick で)

duration: 60
level: 0

# 死んだときの足場数リセット

reset: true

# 見た目の足場の最大値
# 上げ過ぎたら原因不明のバグで足場が分離します。負荷も大きくなります。

max: 50



